export const facts = [
  "Japan has more than 6,800 islands.",
  "The Amazon rainforest produces about 20% of the world's oxygen.",
  "Canada has more lakes than all other countries combined.",
  "France is the most visited country in the world.",
  "Australia is wider than the moon.",
  "Italy has the most UNESCO World Heritage Sites in the world.",
  "India is the largest democracy in the world.",
  "Iceland has no mosquitoes.",
  "Switzerland has over 1,500 lakes.",
  "Chocolate originated in Mexico.",
  "The pyramids in Egypt were built over 4,500 years ago.",
  "Norway experiences 24 hours of daylight during summer in some areas.",
  "The Great Wall of China is over 21,000 kilometers long.",
  "South Africa has three capital cities.",
  "Germany has over 1,000 types of sausages.",
  "Brazil is home to the largest river by volume, the Amazon River.",
  "Russia spans 11 time zones.",
  "The Sahara Desert is the largest hot desert in the world.",
  "Mount Everest is the highest mountain above sea level.",
  "Venice in Italy is built on more than 100 small islands.", 
  "Israel is the only country in the world where you can visit snow, desert, and coral reefs all within a few hours of travel.",
  "Israel has the highest number of startups per capita in the world, earning it the nickname 'Startup Nation'."
];